version: '3.9'
services:
    db_mysql_python:
      image: mysql:latest
      container_name: 'mysql_python'
      environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_DATABASE=clean_database
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=mypassword
      volumes:
        - mysql-python-data:/var/lib/mysql
      ports:
        - 3306:3306

volumes:
    mysql-python-data: